# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["2.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

        exclude:
          - os: macos-latest
            python-version: "2.7"
          - os: windows-latest
            python-version: "2.7"

      fail-fast: false
    env:
      LD_LIBRARY_PATH: ''
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: MatteoH2O1999/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        cache-build: true
    - name: Build librtlsdr
      if: ${{ matrix.python-version == 2.7 }}
      run: |
        sudo apt-get install -y libusb-1.0-0-dev
        cd tools/ci
        ./install-librtlsdr.sh
        cd ../..
        echo "NEW_LD_LIBPATH=$HOME/.local:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -U pytest pytest-cov
        pip install numpy
    - name: Install py3 dependencies
      run: pip install pytest-asyncio
      if: ${{ matrix.python-version != 2.7 }}
    - name: Install pyrtlsdr with lib
      if: ${{ matrix.python-version != 2.7 }}
      run: pip install -e '.[lib]'
    - name: Install pyrtlsdr
      run: pip install -e .
      if: ${{ matrix.python-version == 2.7 }}
    - name: Test with pytest
      shell: bash
      run: |
        py.test --cov-config .coveragerc --cov=rtlsdr
        py.test --cov-append --cov-config .coveragerc --cov=rtlsdr --no-overrides --pyargs tests/no_override_client_mode.py
        py.test --cov-append --cov-config .coveragerc --cov=rtlsdr --no-overrides --pyargs tests/no_override_dll_loader.py
      env:
        LD_LIBRARY_PATH: ${{ env.NEW_LD_LIBPATH }}
    - name: Set up Python3 for coveralls
      if: ${{ matrix.python-version == 2.7 }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upload to Coveralls
      run: |
        python -m pip install coveralls
        python -m coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: run-${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
